// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl34D93NnalmYUuZoGv4-nvEuTbc6PsEA',
    appId: '1:863470174934:web:fc36c7acac23233822ff77',
    messagingSenderId: '863470174934',
    projectId: 'sadafdatabasestore',
    authDomain: 'sadafdatabasestore.firebaseapp.com',
    storageBucket: 'sadafdatabasestore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyiNQdXqNZmovLPTD6J_OIbPQ86p_Mx7g',
    appId: '1:863470174934:android:a7145995d308906d22ff77',
    messagingSenderId: '863470174934',
    projectId: 'sadafdatabasestore',
    storageBucket: 'sadafdatabasestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tpmqDD49Fd1boD54qfj8cErUiATYUuk',
    appId: '1:863470174934:ios:5b111c7eca4e9f5122ff77',
    messagingSenderId: '863470174934',
    projectId: 'sadafdatabasestore',
    storageBucket: 'sadafdatabasestore.appspot.com',
    iosClientId: '863470174934-r3ptijq8hobngvvmc1cs0s44i45bital.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
