// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwS1V-bfNthjkvfAUJqCspuhDj6UekaU',
    appId: '1:222957812256:web:3ac726c09ac851f1ba5a45',
    messagingSenderId: '222957812256',
    projectId: 'sadaf123',
    authDomain: 'sadaf123.firebaseapp.com',
    storageBucket: 'sadaf123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKG3iQ73zjCkXFBCLGGZNcM8nBP39FAnE',
    appId: '1:222957812256:android:c2bce942ce6437f8ba5a45',
    messagingSenderId: '222957812256',
    projectId: 'sadaf123',
    storageBucket: 'sadaf123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2P77-O0vV3mukYC9r0youd1Z97YZmWsw',
    appId: '1:222957812256:ios:063da0ddd8c8b79fba5a45',
    messagingSenderId: '222957812256',
    projectId: 'sadaf123',
    storageBucket: 'sadaf123.appspot.com',
    iosClientId: '222957812256-fan4l6pusi2i7lrp7r55k2tuc50us3fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2P77-O0vV3mukYC9r0youd1Z97YZmWsw',
    appId: '1:222957812256:ios:063da0ddd8c8b79fba5a45',
    messagingSenderId: '222957812256',
    projectId: 'sadaf123',
    storageBucket: 'sadaf123.appspot.com',
    iosClientId: '222957812256-fan4l6pusi2i7lrp7r55k2tuc50us3fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
