// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBwu0wYVykuah-w5cZPWT_TzajtYhi-0',
    appId: '1:119495593616:web:2e808b234a5de6872ed215',
    messagingSenderId: '119495593616',
    projectId: 'sad1234',
    authDomain: 'sad1234.firebaseapp.com',
    storageBucket: 'sad1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTKpk4bfz7FktIeK5kLOrezGXIPUOXt4',
    appId: '1:119495593616:android:1e9fc8df0962414c2ed215',
    messagingSenderId: '119495593616',
    projectId: 'sad1234',
    storageBucket: 'sad1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUzKE5bhhBNYgD0rfDmue5cLn8ywM4CBY',
    appId: '1:119495593616:ios:1339b7bff89b7b042ed215',
    messagingSenderId: '119495593616',
    projectId: 'sad1234',
    storageBucket: 'sad1234.appspot.com',
    iosClientId: '119495593616-2921uvtntll661min96adklmtlc28amn.apps.googleusercontent.com',
    iosBundleId: 'com.example.class7',
  );
}
