// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0rOLksgXASbpQ3tAYrRYIfATxMHyJfQ',
    appId: '1:20522047127:web:327871cdeec8630acabbd2',
    messagingSenderId: '20522047127',
    projectId: 'sad2310',
    authDomain: 'sad2310.firebaseapp.com',
    storageBucket: 'sad2310.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDH1viXyduIAOCtqLFibtL0MpZasxHY8',
    appId: '1:20522047127:android:f24bd352b2b39c8fcabbd2',
    messagingSenderId: '20522047127',
    projectId: 'sad2310',
    storageBucket: 'sad2310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnabohj9jxb9izWxtOh7aJbyeXdEiTWC4',
    appId: '1:20522047127:ios:c89115aac4735248cabbd2',
    messagingSenderId: '20522047127',
    projectId: 'sad2310',
    storageBucket: 'sad2310.appspot.com',
    iosClientId: '20522047127-ashh69vree8q7pl05hiik97fs9lbb9uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.class7',
  );
}
